{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# vòng lặp for (lặp đi lặp lại 1 phần tử)\n",
    "Cú pháp\n",
    "```ruby\n",
    "for i in 0..5\n",
    "    puts \"Value of local variable is #{i}\n",
    "end\n",
    "```\n",
    "\n",
    "## break\n",
    "```ruby\n",
    "for i in 0..5\n",
    "    if i > 2 then\n",
    "        break\n",
    "    end\n",
    "    puts \"value of local variable is #{i}\"\n",
    "end\n",
    "```\n",
    "## next\n",
    "```ruby\n",
    "for i in 0..5\n",
    "    if i < 2 then\n",
    "        next\n",
    "    end\n",
    "    puts \"value of local variable is #{i}\"\n",
    "end\n",
    "```\n",
    "\n",
    "##  ví dụ\n",
    "```ruby\n",
    "string = [\"one\", \"two\", \"four\", \"five\"]\n",
    "string.inject(0) do |sum, str|\n",
    "    next if str.size == 4\n",
    "    sum + str.size\n",
    "end\n",
    "```\n",
    "--> trả về nill, làm sao để hàm trả về kết quả đúng\n",
    "```ruby\n",
    "string = [\"one\", \"two\", \"four\", \"five\"]\n",
    "string.inject(0) do |sum, str|\n",
    "    next sum if str.size == 4 # sau khi next giá trị sẽ đc gắn vào biến sum và lưu lại ở vòng lặp sau\n",
    "    sum + str.size\n",
    "end\n",
    "```\n",
    "--> 6\n",
    "## Redo:thực hiện lại 1 hành động\n",
    "```ruby\n",
    "# hàm nhập vào 1 số chẵn\n",
    "def num \n",
    "    for i in 0..3\n",
    "        print \"enter a number: \"\n",
    "        num = gets.to_i\n",
    "\n",
    "        if num % 2 != 0\n",
    "            redo # nếu nhập sai sẽ bắt đầu lại vòng lặp\n",
    "        end\n",
    "        puts \"i: #{i} - so ban nhap la #{num}\"\n",
    "    end\n",
    "end\n",
    "```\n",
    "--> vòng lặp 3 lần khi nhập đúng 3 lần và thoát\n",
    "## Retry: try again khi gặp exception\n",
    "- lưu ý: chương trình có thể rơi vào vòng lặp vô hạn nếu ko có cơ chế dừng\n",
    "```ruby\n",
    "begin\n",
    "    retries ||= 0 # gắn giá trị = 0\n",
    "    puts \"try ##{ retries }\"\n",
    "    raise \"the roof\"# in ra lỗi\n",
    "rescue\n",
    "    retry if (retries +=1) < 3 # nếu < 3 thì lại thực hiện lại đến rescue\n",
    "end\n",
    "```\n",
    "# Select, map, inject\n",
    "## map: lấy tất cả đối tượng sử dụng chúng và chạy biểu thức trong block\n",
    "```ruby\n",
    "my_array = [1, 2, ,3 4, 5, 6, 8, 100]\n",
    "my_array.map{|item| item *2} # nhân all phần tử cho 2\n",
    "my_array.map{|item| item %2} # chia all phần tử cho 2\n",
    "my_array.map{|item| item %2 == 0} # nhân all phần tử cho 2\n",
    "[false, true, false, true, false, true, false, true, true]\n",
    "\n",
    "```\n",
    "##select : trả ra các giá trị thỏa mãn \n",
    "```ruby\n",
    "my_array.select{|item| item %2 == 0} \n",
    "#[2, 4, 6, 8, 100]\n",
    "```\n",
    "- Có thể sử dụng select trong hash\n",
    "## inject : cung cấp 1 biến số mà cập nhập giá trị của biến số khi mỗi phần tử đc duyệt qua\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
